Thu Feb 17 08:48:18 2022  탐색 오류 발생
Thu Feb 17 08:48:18 2022  Traceback (most recent call last):
  File "/Users/kimyoungjun/PycharmProjects/pythonProject/0.2/Bot.py", line 42, in <module>
    found = search2(upbit, excluded_tickers)
  File "/Users/kimyoungjun/PycharmProjects/pythonProject/0.2/search.py", line 21, in search2
    moving_average_20 = get_tickers_moving_average(tickers,'close',20,day,timeunit)
  File "/Users/kimyoungjun/PycharmProjects/pythonProject/0.2/modules.py", line 179, in get_tickers_moving_average
    data_list = get_history(tickers,200,timeunit)
  File "/Users/kimyoungjun/PycharmProjects/pythonProject/0.2/modules.py", line 123, in get_history
    data = pyupbit.get_ohlcv(ticker=ticker, interval=timeunit, count=length)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyupbit/quotation_api.py", line 103, in get_ohlcv
    contents, req_limit_info = _call_public_api(url, market=ticker, count=query_count, to=to)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyupbit/request_api.py", line 44, in _call_public_api
    resp = requests.get(url, params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
KeyboardInterrupt

